server:
  port: 8000

spring:
  rabbitmq:
    virtual-host: /order
    username: admin
    password: 123456
    addresses: localhost:5672
    # 消费端配置
    listener:
      simple:
        concurrency: 5            # 并发数
        max-concurrency: 10       # 最大并发数
        acknowledge-mode: manual  # 手动确认消息
        prefetch: 1
